/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CharteRouteImport } from './routes/charte'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReglementRouteImport } from './routes/reglement'
import { Route as StatutsRouteImport } from './routes/statuts'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSuponeAiRouteImport } from './routes/projects.supone-ai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CharteRoute = CharteRouteImport.update({
  id: '/charte',
  path: '/charte',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglementRoute = ReglementRouteImport.update({
  id: '/reglement',
  path: '/reglement',
  getParentRoute: () => rootRouteImport,
} as any)
const StatutsRoute = StatutsRouteImport.update({
  id: '/statuts',
  path: '/statuts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsSuponeAiRoute = ProjectsSuponeAiRouteImport.update({
  id: '/supone-ai',
  path: '/supone-ai',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/charte': typeof CharteRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reglement': typeof ReglementRoute
  '/statuts': typeof StatutsRoute
  '/projects/supone-ai': typeof ProjectsSuponeAiRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/charte': typeof CharteRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/reglement': typeof ReglementRoute
  '/statuts': typeof StatutsRoute
  '/projects/supone-ai': typeof ProjectsSuponeAiRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/charte': typeof CharteRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reglement': typeof ReglementRoute
  '/statuts': typeof StatutsRoute
  '/projects/supone-ai': typeof ProjectsSuponeAiRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/charte'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/join'
    | '/projects'
    | '/reglement'
    | '/statuts'
    | '/projects/supone-ai'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/charte'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/join'
    | '/reglement'
    | '/statuts'
    | '/projects/supone-ai'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/charte'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/join'
    | '/projects'
    | '/reglement'
    | '/statuts'
    | '/projects/supone-ai'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CharteRoute: typeof CharteRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  JoinRoute: typeof JoinRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReglementRoute: typeof ReglementRoute
  StatutsRoute: typeof StatutsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charte': {
      id: '/charte'
      path: '/charte'
      fullPath: '/charte'
      preLoaderRoute: typeof CharteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglement': {
      id: '/reglement'
      path: '/reglement'
      fullPath: '/reglement'
      preLoaderRoute: typeof ReglementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statuts': {
      id: '/statuts'
      path: '/statuts'
      fullPath: '/statuts'
      preLoaderRoute: typeof StatutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/supone-ai': {
      id: '/projects/supone-ai'
      path: '/supone-ai'
      fullPath: '/projects/supone-ai'
      preLoaderRoute: typeof ProjectsSuponeAiRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsSuponeAiRoute: typeof ProjectsSuponeAiRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSuponeAiRoute: ProjectsSuponeAiRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CharteRoute: CharteRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  JoinRoute: JoinRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReglementRoute: ReglementRoute,
  StatutsRoute: StatutsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
